name: pre-commit

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install uv
      uses: astral-sh/setup-uv@v4
    - name: Install dependencies
      run: |
        uv sync --group dev
    - name: Run pre-commit
      run: |
        uv run pre-commit run --all-files
